name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  publish_upload:
    name: Publish and upload
    runs-on: ubuntu-latest
    container:
      image: archlinux/archlinux:base-devel

    steps:
      - name: Install Git & Go
        run: pacman -Syu --needed --noconfirm git go

      - uses: actions/checkout@v3

      - name: Build
        run: |
          mkdir package-archlinux-x86-64-v2 \
                package-archlinux-x86-64-v3 \
                package-linux-x86-64-v2 \
                package-linux-x86-64-v3 \
                package-linux-arm64 \
                package-windows-x86-64-v2 \
                package-windows-x86-64-v3 \
                package-windows-arm64

          env GOAMD64=v2 go build -v -trimpath -ldflags '-s -w' -o package-archlinux-x86-64-v2/ ./cmd/swgp-go
          env GOAMD64=v3 go build -v -trimpath -ldflags '-s -w' -o package-archlinux-x86-64-v3/ ./cmd/swgp-go
          env CGO_ENABLED=0 GOAMD64=v2 go build -v -trimpath -ldflags '-s -w' -o package-linux-x86-64-v2/ ./cmd/swgp-go
          env CGO_ENABLED=0 GOAMD64=v3 go build -v -trimpath -ldflags '-s -w' -o package-linux-x86-64-v3/ ./cmd/swgp-go
          env CGO_ENABLED=0 GOARCH=arm64 go build -v -trimpath -ldflags '-s -w' -o package-linux-arm64/ ./cmd/swgp-go
          env CGO_ENABLED=0 GOAMD64=v2 GOOS=windows go build -v -trimpath -ldflags '-s -w' -o package-windows-x86-64-v2/ ./cmd/swgp-go
          env CGO_ENABLED=0 GOAMD64=v3 GOOS=windows go build -v -trimpath -ldflags '-s -w' -o package-windows-x86-64-v3/ ./cmd/swgp-go
          env CGO_ENABLED=0 GOOS=windows GOARCH=arm64 go build -v -trimpath -ldflags '-s -w' -o package-windows-arm64/ ./cmd/swgp-go

      - name: Get version
        id: get_version
        run: echo "::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)"

      - name: Package
        env:
          ZSTD_CLEVEL: 19
          ZSTD_NBTHREADS: 2
        run: |
          cd package-archlinux-x86-64-v2/
          tar -acf ../swgp-go-${{ steps.get_version.outputs.VERSION }}-archlinux-x86-64-v2.tar.zst .
          cd ../package-archlinux-x86-64-v3/
          tar -acf ../swgp-go-${{ steps.get_version.outputs.VERSION }}-archlinux-x86-64-v3.tar.zst .
          cd ../package-linux-x86-64-v2/
          tar -acf ../swgp-go-${{ steps.get_version.outputs.VERSION }}-linux-x86-64-v2.tar.zst .
          cd ../package-linux-x86-64-v3/
          tar -acf ../swgp-go-${{ steps.get_version.outputs.VERSION }}-linux-x86-64-v3.tar.zst .
          cd ../package-linux-arm64/
          tar -acf ../swgp-go-${{ steps.get_version.outputs.VERSION }}-linux-arm64.tar.zst .
          cd ../package-windows-x86-64-v2/
          tar -acf ../swgp-go-${{ steps.get_version.outputs.VERSION }}-windows-x86-64-v2.tar.zst .
          cd ../package-windows-x86-64-v3/
          tar -acf ../swgp-go-${{ steps.get_version.outputs.VERSION }}-windows-x86-64-v3.tar.zst .
          cd ../package-windows-arm64/
          tar -acf ../swgp-go-${{ steps.get_version.outputs.VERSION }}-windows-arm64.tar.zst .

      - name: Upload release assets
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: swgp-go-*.tar.zst
          tag: ${{ github.ref }}
          file_glob: true
          prerelease: true
